// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zup.AdministracaoClientes.Data.Context;

namespace Zup.AdministracaoClientes.Data.Migrations
{
    [DbContext(typeof(AdministracaoClientesContext))]
    partial class AdministracaoClientesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zup.AdministracaoClientes.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Zup.AdministracaoClientes.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("Zup.AdministracaoClientes.Domain.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("CPF")
                                .HasColumnType("varchar(11)")
                                .HasMaxLength(11);

                            b1.HasKey("ClienteId");

                            b1.ToTable("Cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsMany("Zup.AdministracaoClientes.Domain.ValueObjects.Endereco", "Enderecos", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("varchar(250)")
                                .HasMaxLength(250);

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("varchar(250)")
                                .HasMaxLength(250);

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("varchar(20)")
                                .HasMaxLength(20);

                            b1.Property<short?>("Numero")
                                .HasColumnType("smallint");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasColumnType("varchar(25)")
                                .HasMaxLength(25);

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("varchar(250)")
                                .HasMaxLength(250);

                            b1.HasKey("ClienteId", "Id");

                            b1.ToTable("Endereco");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");

                            b1.OwnsOne("Zup.AdministracaoClientes.Domain.ValueObjects.CEP", "CEP", b2 =>
                                {
                                    b2.Property<Guid>("EnderecoClienteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("EnderecoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnName("CEP")
                                        .HasColumnType("varchar(100)");

                                    b2.HasKey("EnderecoClienteId", "EnderecoId");

                                    b2.ToTable("Endereco");

                                    b2.WithOwner()
                                        .HasForeignKey("EnderecoClienteId", "EnderecoId");
                                });
                        });

                    b.OwnsMany("Zup.AdministracaoClientes.Domain.ValueObjects.Telefone", "Telefones", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<long>("Value")
                                .HasColumnName("Numero")
                                .HasColumnType("bigint");

                            b1.HasKey("ClienteId", "Id");

                            b1.ToTable("Telefone");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
