version: '3.4'

services:

  db:
    container_name: administracao.clientes.sqlserver
    ports:
      - 1433:1433
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=!AsDqWe123@@

  api:
    container_name: administracao.clientes.api
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: src/Zup.AdministracaoClientes.API/Dockerfile
    depends_on:
      - db